package cu.uci.abos.core.validation;


public enum DecoratorType {
	REQUIRED_FIELD, ERROR, WARNING, INFORMATION, CONTENT_PROPOSAL, NUMBER_ONLY, NUMBER_POINT_ONLY, EMAIL, URL, DOUBLE, DATE_RANGE, ALPHA_NUMERICS_SPACES, ALPHA_SPACES, NUMBER, DOUBLE_SPACES, ALPHA, ANY_TIME_BACKWARD, ANY_TIME_FORWARD, ALPHANUMERIC_AND_UNDERSCORE, ALL_BUT_NO_OTHER_REPEAT_CONSECUTIVE, LENGTH_FIELD, NUMBER_ONLY_NOT_START_WITH_CERO, DOMAIN, IP, PORT, ALPHA_SPACES_GUION, ALPHA_NUMERIC, USER_NAME
}

